# Generated by Django 4.2 on 2023-04-26 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(max_length=10)),
                ('phone_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.record')),
            ],
        ),
    ]
