# Generated by Django 4.2 on 2023-05-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='phone_no',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='f_name',
        ),
    ]
