# Generated by Django 4.2 on 2023-05-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_price_sale_product_sale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_debt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
