# Generated by Django 4.2 on 2023-05-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_phone_no_sale_client_remove_sale_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='f_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
