# Generated by Django 4.2 on 2023-05-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_calculations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculations',
        ),
    ]
