# Generated by Django 4.2 on 2023-05-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_sale_product_alter_sale_served_by_delete_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='pay',
            field=models.CharField(choices=[('M-PESA', 'M-PESA'), ('CASH', 'CASH')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
