# Generated by Django 4.2 on 2023-05-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_delete_calculations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
