# Generated by Django 4.2 on 2023-05-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
