# Generated by Django 4.2 on 2023-05-18 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_debt_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
