# Generated by Django 4.2 on 2023-05-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='user',
        ),
        migrations.AddField(
            model_name='sale',
            name='pay',
            field=models.CharField(choices=[('M-PESA', 'M-PESA'), ('CASH', 'CASH')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
