# Generated by Django 4.2 on 2023-05-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_sale_user_sale_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
