# Generated by Django 4.2 on 2023-05-10 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0018_alter_record_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.route'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
