# Generated by Django 4.2 on 2023-05-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_debt_date_alter_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='image',
        ),
    ]
